// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 2);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.elevate.attempts", 0);
user_pref("app.update.langpack.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1642772348);
user_pref("app.update.lastUpdateTime.background-update-timer", 1642818537);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1642818659);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1642818899);
user_pref("app.update.lastUpdateTime.region-update-timer", 1642390260);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1642767323);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1642818779);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1642772228);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1642390380);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 1642772108);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1642771988);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1605246142649");
user_pref("security.sandbox.content.tempDirSuffix", "{4663f837-4f5d-438f-bb10-30a0e7c49a67}");
user_pref("toolkit.backgroundtasks.loglevel", "error");
user_pref("toolkit.startup.last_success", 1642837224);
